#!/bin/bash

#SBATCH -J solve_sudoku               # Job name
#SBATCH -o job.%j.out         # Name of stdout output file (%j expands to jobId)
#SBATCH -N 1                    # number of nodes
#SBATCH --ntasks=1              # 1 proces
#SBATCH --cpus-per-task=32      # 32 CPU cores for threads
#SBATCH -t 01:00:00           # Run time (hh:mm:ss) - 1.5 hours

mkdir -p results2

for file in puzzles/puzzle25_*.txt
do
        [ -e "$file" ] || continue
        base=$(basename "$file" .txt)
        echo "Running $file"
        timeout 900s ./a2.out "$file" > "results2/${base}.out"
done
